[workspace]
members = [
    "crates/nesstar-core",
    "crates/nesstar-cli",
    "crates/nesstar-gui",
]
resolver = "2"

[workspace.package]
version = "1.0.7"
edition = "2024"
license = "MIT"
authors = ["Abhinav Kumar"]
repository = "https://github.com/abhinavjnu/nesstar-converter"
homepage = "https://github.com/abhinavjnu/nesstar-converter"
documentation = "https://docs.rs/nesstar-core"
readme = "README.md"

[workspace.lints.rust]
unsafe_code = "deny"

[profile.release]
codegen-units = 1
lto = "thin"
strip = "symbols"
